### PR TITLE
PHP7 Installation Support

### PR DESCRIPTION
**Pull request by mtwilliams5**
Some changes to the installation files to allow Nova to install on PHP7 without errors. This involved:

Updating default driver to use mysqli (if the mysqli extension isn't installed in PHP, it'll default back to mysql)
Due to the new default MySQL mode in 5.7 of `STRICT_TRANS_TABLES`, DB fields have been updated to either include a default or explicitly allow null when there's a chance that the field won't be set.

I've also updated the `CI_Model` and `Thresher` classes to use an appropriately named constructor function to clear a deprecated notice for both (not specifically related to the installation process, but still part of PHP7 upgrades)

Not specifically related to PHP7, but I've also updated the templates for installs and upgrades to allow jQuery to be loaded over https.

Note one of the new default modes I've not tried to accommodate: `ONLY_FULL_GROUP_BY`, since that would require quite a significant re-working of DB queries.

I've gone through a quick test of all the pages on Homestead with v 7.2.0 (with `ONLY_FULL_GROUP_BY` disabled) to ensure there are no errors with the dev data loaded, but I don't know how extensively you tend to test Nova 2 across different versions and environments.

Feel free to cherry pick what bits to incorporate out of this; if you're not bothered about supporting `STRICT_TRANS_TABLES` then you can probably drop all of the changes in `nova/modules/assets/install/fields.php`, which will make the changes smaller in scope.

### CODE REVIEW

**Comment by agentphoenix** [comment]
Thanks for these @mtwilliams5 

I actually worked on some of these a little bit a couple weeks back just to try and get my dev environment back up and running, but never got them all taken care of, so this will be a huge help! Have you done any testing with these changes on PHP lower than 7? Just wanting to make sure we don't introduce any issues for folks who are on servers who haven't been upgraded yet.

**Comment by mtwilliams5** [comment]
Sorry, didn't see your response for some reason.

I did do a quick test through each of the pages on PHP 5.6 to check that it doesn't throw any errors (Homestead's multiple PHP versions is great for that!)

**Comment by ebollens** [comment]
> Have you done any testing with these changes on PHP lower than 7? Just wanting to make sure we don't introduce any issues for folks who are on servers who haven't been upgraded yet.

These changes all look safe to me too.

**Comment by agentphoenix** [comment]
Gonna try to do some testing on these changes so that they can be rolled in to the GDPR updates by May 25th.

**Pull request merged**
